"""Add public column to posts

Revision ID: a69b71f925bc
Revises: 5c4b2dfa8570
Create Date: 2025-03-25 22:04:40.410445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69b71f925bc'
down_revision: Union[str, None] = '5c4b2dfa8570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'public')
    # ### end Alembic commands ###
