"""add cascade delete to like model

Revision ID: f52be9b255ce
Revises: 2883db31cee3
Create Date: 2025-04-06 11:50:17.193125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52be9b255ce'
down_revision: Union[str, None] = '2883db31cee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_likes_post_id_fkey', 'posts_likes', type_='foreignkey')
    op.create_foreign_key(None, 'posts_likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts_likes', type_='foreignkey')
    op.create_foreign_key('posts_likes_post_id_fkey', 'posts_likes', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
